export default {
  at: "2024-09-15T21:34:00.467Z",
  products: [
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "anim enim pariatur consequat",
      name: "consectetur",
      price: 838.6,
      tmpProperty: undefined,
      activePromoId: 40,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "quis incididunt mollit in",
      name: "dolor",
      price: 1684.96,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam pariatur elit sunt",
      name: "amet",
      price: 865.85,
      tmpProperty: undefined,
      activePromoId: 0,
    },
    {
      description: "non adipisicing aute nostrud",
      name: "sint",
      price: 640.04,
      tmpProperty: undefined,
      activePromoId: 81,
    },
    {
      description: "et labore magna aute",
      name: "deserunt",
      price: 1301.48,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "aliquip officia laborum esse",
      name: "ipsum",
      price: 407.72,
      tmpProperty: undefined,
      activePromoId: 84,
    },
    {
      description: "id minim anim ullamco",
      name: "do",
      price: 1297.77,
      tmpProperty: undefined,
      activePromoId: 67,
    },
    {
      description: "velit consectetur aute consequat",
      name: "aliquip",
      price: 1483.41,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: "pariatur proident exercitation dolore",
      name: "elit",
      price: 913.39,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "aliqua ut deserunt nisi",
      name: "Lorem",
      price: 947.79,
      tmpProperty: undefined,
      activePromoId: 74,
    },
    {
      description: "duis incididunt officia in",
      name: "commodo",
      price: 616.97,
      tmpProperty: undefined,
      activePromoId: 8,
    },
    {
      description: "pariatur sit reprehenderit velit",
      name: "pariatur",
      price: 555.11,
      tmpProperty: undefined,
      activePromoId: 72,
    },
    {
      description: "laboris do amet dolore",
      name: "ad",
      price: 1304.31,
      tmpProperty: undefined,
      activePromoId: 29,
    },
    {
      description: "incididunt ad ad voluptate",
      name: "amet",
      price: 1506.11,
      tmpProperty: undefined,
      activePromoId: 80,
    },
    {
      description: "sit magna eiusmod eu",
      name: "incididunt",
      price: 1135.55,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "elit id laboris dolore",
      name: "id",
      price: 1353.08,
      tmpProperty: undefined,
      activePromoId: 40,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "excepteur voluptate enim qui",
      name: "cupidatat",
      price: 1299.92,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: "est consequat minim minim",
      name: "sunt",
      price: 485.67,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cillum ut tempor cupidatat",
      name: "sit",
      price: 589.76,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: "ad commodo commodo enim",
      name: "adipisicing",
      price: 934.48,
      tmpProperty: undefined,
      activePromoId: 71,
    },
    {
      description: "nulla sunt laboris velit",
      name: "cupidatat",
      price: 501.45,
      tmpProperty: undefined,
      activePromoId: 90,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "ipsum qui fugiat esse",
      name: "officia",
      price: 731.59,
      tmpProperty: undefined,
      activePromoId: 85,
    },
    {
      description: "aliquip eiusmod duis qui",
      name: "reprehenderit",
      price: 596.11,
      tmpProperty: undefined,
      activePromoId: 87,
    },
    {
      description: "id do nulla consequat",
      name: "Lorem",
      price: 1973.3,
      tmpProperty: undefined,
      activePromoId: 54,
    },
    {
      description: "esse irure officia et",
      name: "ullamco",
      price: 300.33,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eu reprehenderit eiusmod do",
      name: "reprehenderit",
      price: 1756.62,
      tmpProperty: undefined,
      activePromoId: 24,
    },
    {
      description: "nostrud velit in eu",
      name: "ipsum",
      price: 658.03,
      tmpProperty: undefined,
      activePromoId: 14,
    },
    {
      description: "proident amet minim ad",
      name: "Lorem",
      price: 806.74,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: "proident sit amet esse",
      name: "mollit",
      price: 389.98,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat sit nulla ad",
      name: "voluptate",
      price: 885.69,
      tmpProperty: undefined,
      activePromoId: 15,
    },
    {
      description: "sit proident consectetur commodo",
      name: "duis",
      price: 1851.81,
      tmpProperty: undefined,
      activePromoId: 55,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "excepteur ullamco magna anim",
      name: "adipisicing",
      price: 1183.77,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "voluptate id ullamco dolor",
      name: "ea",
      price: 1951.78,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aute ipsum veniam officia",
      name: "et",
      price: 1747.41,
      tmpProperty: undefined,
      activePromoId: 59,
    },
    {
      description: "esse ad consectetur deserunt",
      name: "occaecat",
      price: 115.12,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "anim id esse nostrud",
      name: "tempor",
      price: 1278.51,
      tmpProperty: undefined,
      activePromoId: 51,
    },
    {
      description: "nisi in voluptate magna",
      name: "duis",
      price: 331.12,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "minim labore mollit culpa",
      name: "minim",
      price: 1109.75,
      tmpProperty: undefined,
      activePromoId: 77,
    },
    {
      description: "veniam veniam mollit enim",
      name: "consectetur",
      price: 1511.83,
      tmpProperty: undefined,
      activePromoId: 43,
    },
    {
      description: "irure eiusmod officia Lorem",
      name: "duis",
      price: 428.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliqua amet ad commodo",
      name: "do",
      price: 967.32,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laborum elit excepteur consequat",
      name: "veniam",
      price: 1446.42,
      tmpProperty: undefined,
      activePromoId: 23,
    },
    {
      description: "et reprehenderit anim eiusmod",
      name: "eu",
      price: 1583.67,
      tmpProperty: undefined,
      activePromoId: 76,
    },
    {
      description: "culpa ea ipsum nostrud",
      name: "fugiat",
      price: 377.74,
      tmpProperty: undefined,
      activePromoId: 81,
    },
    {
      description: "officia aliqua commodo voluptate",
      name: "voluptate",
      price: 446.57,
      tmpProperty: undefined,
      activePromoId: 41,
    },
    {
      description: "cillum incididunt ad ipsum",
      name: "velit",
      price: 1680.66,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "magna laboris fugiat est",
      name: "nostrud",
      price: 1991.77,
      tmpProperty: undefined,
      activePromoId: 70,
    },
    {
      description: "fugiat et do est",
      name: "eu",
      price: 896.51,
      tmpProperty: undefined,
      activePromoId: 66,
    },
    {
      description: "amet laborum Lorem ex",
      name: "nisi",
      price: 725.47,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "quis qui officia ipsum",
      name: "non",
      price: 240.7,
      tmpProperty: undefined,
      activePromoId: 22,
    },
    {
      description: "dolore nostrud consequat quis",
      name: "tempor",
      price: 1822.17,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: "esse sint cupidatat consectetur",
      name: "exercitation",
      price: 1545.49,
      tmpProperty: undefined,
      activePromoId: 88,
    },
    {
      description: "minim laborum dolor labore",
      name: "irure",
      price: 614.97,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "enim ad fugiat sit",
      name: "cillum",
      price: 1039.36,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "officia sit velit incididunt",
      name: "quis",
      price: 217.14,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "mollit labore aliqua dolore",
      name: "ipsum",
      price: 1972.46,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "mollit consequat duis ullamco",
      name: "eu",
      price: 1564.75,
      tmpProperty: undefined,
      activePromoId: 64,
    },
    {
      description: "minim consectetur dolore commodo",
      name: "enim",
      price: 1200.85,
      tmpProperty: undefined,
      activePromoId: 8,
    },
    {
      description: "laborum occaecat incididunt ut",
      name: "qui",
      price: 1855.26,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laborum veniam elit amet",
      name: "do",
      price: 1813.21,
      tmpProperty: undefined,
      activePromoId: 94,
    },
    {
      description: "tempor voluptate et do",
      name: "mollit",
      price: 1680.89,
      tmpProperty: undefined,
      activePromoId: 46,
    },
    {
      description: "nisi nisi consequat eiusmod",
      name: "laboris",
      price: 411.4,
      tmpProperty: undefined,
      activePromoId: 4,
    },
    {
      description: "consectetur in culpa nostrud",
      name: "aute",
      price: 1866.27,
      tmpProperty: undefined,
      activePromoId: 78,
    },
    {
      description: "laboris voluptate nulla tempor",
      name: "aliqua",
      price: 1331.36,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "labore excepteur incididunt et",
      name: "laboris",
      price: 1653.33,
      tmpProperty: undefined,
      activePromoId: 34,
    },
    {
      description: "velit commodo incididunt fugiat",
      name: "labore",
      price: 1695.07,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "duis eu est aute",
      name: "non",
      price: 1029.61,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: "aliquip cillum id deserunt",
      name: "enim",
      price: 131.52,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ex est Lorem adipisicing",
      name: "velit",
      price: 1362.7,
      tmpProperty: undefined,
      activePromoId: 93,
    },
    {
      description: "ipsum voluptate tempor Lorem",
      name: "consectetur",
      price: 169.09,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "qui magna eu eiusmod",
      name: "nisi",
      price: 1063.06,
      tmpProperty: undefined,
      activePromoId: 97,
    },
    {
      description: "eiusmod sit minim minim",
      name: "nulla",
      price: 1403.73,
      tmpProperty: undefined,
      activePromoId: 0,
    },
    {
      description: "ex adipisicing deserunt deserunt",
      name: "quis",
      price: 1788.89,
      tmpProperty: undefined,
      activePromoId: 98,
    },
    {
      description: "sit reprehenderit culpa veniam",
      name: "pariatur",
      price: 748.35,
      tmpProperty: undefined,
      activePromoId: 42,
    },
    {
      description: "culpa magna ut amet",
      name: "ipsum",
      price: 1006.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ipsum esse dolor irure",
      name: "voluptate",
      price: 503.2,
      tmpProperty: undefined,
      activePromoId: 92,
    },
    {
      description: "voluptate dolore commodo qui",
      name: "ut",
      price: 423.97,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "anim incididunt proident ullamco",
      name: "pariatur",
      price: 1166.29,
      tmpProperty: undefined,
      activePromoId: 12,
    },
    {
      description: "ex nisi consequat et",
      name: "pariatur",
      price: 1648.11,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "amet cillum nostrud sit",
      name: "enim",
      price: 1700.15,
      tmpProperty: undefined,
      activePromoId: 19,
    },
    {
      description: "proident culpa labore nulla",
      name: "exercitation",
      price: 633.75,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "voluptate non culpa et",
      name: "nulla",
      price: 430.42,
      tmpProperty: undefined,
      activePromoId: 38,
    },
    {
      description: "quis magna anim consequat",
      name: "non",
      price: 169.05,
      tmpProperty: undefined,
      activePromoId: 47,
    },
    {
      description: "nostrud aliquip amet ullamco",
      name: "consectetur",
      price: 1978.64,
      tmpProperty: undefined,
      activePromoId: 76,
    },
    {
      description: "laboris tempor reprehenderit culpa",
      name: "non",
      price: 1371.39,
      tmpProperty: undefined,
      activePromoId: 22,
    },
    {
      description: "elit nulla eiusmod qui",
      name: "aliqua",
      price: 641.66,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: "Lorem consectetur dolore amet",
      name: "enim",
      price: 833.34,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eu culpa exercitation cupidatat",
      name: "elit",
      price: 1380.19,
      tmpProperty: undefined,
      activePromoId: 81,
    },
    {
      description: "et ea mollit id",
      name: "pariatur",
      price: 227.8,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: "enim magna esse elit",
      name: "ut",
      price: 1758.82,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "mollit fugiat et voluptate",
      name: "id",
      price: 1276.94,
      tmpProperty: undefined,
      activePromoId: 42,
    },
    {
      description: "cillum est veniam deserunt",
      name: "est",
      price: 1990.14,
      tmpProperty: undefined,
      activePromoId: 93,
    },
    {
      description: "laborum anim cupidatat veniam",
      name: "ad",
      price: 204.45,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nisi qui sint in",
      name: "ut",
      price: 1835.63,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ut sit magna eu",
      name: "anim",
      price: 132.4,
      tmpProperty: undefined,
      activePromoId: 15,
    },
    {
      description: "elit excepteur sit aliqua",
      name: "aute",
      price: 868.54,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "incididunt cupidatat ea qui",
      name: "do",
      price: 1251.99,
      tmpProperty: undefined,
      activePromoId: 10,
    },
    {
      description: "nulla proident ea exercitation",
      name: "exercitation",
      price: 1393.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ex sit quis enim",
      name: "reprehenderit",
      price: 1960.61,
      tmpProperty: undefined,
      activePromoId: 45,
    },
    {
      description: "tempor duis do exercitation",
      name: "voluptate",
      price: 126.46,
      tmpProperty: undefined,
      activePromoId: 33,
    },
  ],
};
